### ISSUE TITLE
Convert ips file to dec.

### ISSUE THREAD

**Issue by chukfinley** [mat-1/minecraft-scans#1]
"Each server in the file takes up 6 bytes: 4 bytes for the IPv4 and 2 bytes for the port"
I figured out that 63dd in hex is the port 25565.
0100 64c4 and this is the IP in hex, but how to represent it in Dec with dots?

**Comment by mat-1** [comment]
The ipv4 "human" representation is just the 4 bytes separately as numbers joined by a period. Alternatively, you can bitshift and bitmask the number to get each octet separately.
