### ISSUE TITLE
ips .json format

### ISSUE THREAD

**Issue by Okioki6** [mat-1/minecraft-scans#7]
Can you please provide a .json form of the ips file. I just stumbled upon LiveOverflow and now I'm trying to get his server's ip, but my scan command doesn't find all the possible ones. So I wanted to use your scan, but I don't know how to access the ips. Thanks. Also sorry for asking through issues.

**Comment by mat-1** [comment]
Hi, the README contains an explanation of how to read the file.
> Each server in the file takes up 6 bytes (in big-endian): 4 bytes for the IPv4 and 2 bytes for the port.
